
import { Artwork, Artist } from './types';

export const ARTISTS: Artist[] = [
  { id: 'artist-1', name: 'Nyx Veil', avatarUrl: 'https://picsum.photos/seed/nyx/100/100', coverPhotoUrl: 'https://picsum.photos/seed/nyx-cover/1200/400' },
  { id: 'artist-2', name: 'Vector Shift', avatarUrl: 'https://picsum.photos/seed/vector/100/100', coverPhotoUrl: 'https://picsum.photos/seed/vector-cover/1200/400' },
  { id: 'artist-3', name: 'Glitch Mona', avatarUrl: 'https://picsum.photos/seed/mona/100/100', coverPhotoUrl: 'https://picsum.photos/seed/mona-cover/1200/400' },
  { id: 'artist-4', name: 'Cyra Lumen', avatarUrl: 'https://picsum.photos/seed/cyra/100/100', coverPhotoUrl: 'https://picsum.photos/seed/cyra-cover/1200/400' },
];

export const MOCK_ARTWORKS: Artwork[] = [
  {
    id: '1',
    title: 'Neon Genesis',
    artist: ARTISTS[0],
    imageUrl: 'https://picsum.photos/seed/genesis/600/400',
    description: 'A vibrant depiction of a futuristic city awakening under neon lights. The dawn of a new digital era.',
    tags: ['Sci-Fi', 'Cityscape', 'Neon', 'Digital Art'],
    createdAt: '2024-07-20T10:00:00Z',
    views: 10500,
    likes: 1200,
  },
  {
    id: '2',
    title: 'Cybernetic Bloom',
    artist: ARTISTS[1],
    imageUrl: 'https://picsum.photos/seed/bloom/600/400',
    description: 'Organic forms intertwine with cybernetic enhancements, creating a surreal and beautiful landscape.',
    tags: ['Cyberpunk', 'Organic', 'Surreal', 'Concept Art'],
    createdAt: '2024-07-19T14:30:00Z',
    views: 8700,
    likes: 950,
  },
  {
    id: '3',
    title: 'Quantum Entanglement',
    artist: ARTISTS[2],
    imageUrl: 'https://picsum.photos/seed/quantum/600/400',
    description: 'Abstract representation of quantum particles linked across spacetime. A visual paradox.',
    tags: ['Abstract', 'Quantum Physics', 'Futuristic', '3D Render'],
    createdAt: '2024-07-21T09:15:00Z',
    views: 12300,
    likes: 1500,
  },
  {
    id: '4',
    title: 'Void Walker',
    artist: ARTISTS[0],
    imageUrl: 'https://picsum.photos/seed/voidwalker/600/400',
    description: 'A solitary figure traverses an endless, starlit void. Exploration of the unknown.',
    tags: ['Space', 'Character Design', 'Atmospheric', 'Illustration'],
    createdAt: '2024-07-18T18:00:00Z',
    views: 7500,
    likes: 880,
  },
  {
    id: '5',
    title: 'Synthwave Dreams',
    artist: ARTISTS[3],
    imageUrl: 'https://picsum.photos/seed/synthwave/600/400',
    description: 'A retro-futuristic landscape basked in the purple and pink hues of a digital sunset.',
    tags: ['Synthwave', 'Retro', 'Landscape', '80s Inspired'],
    createdAt: '2024-07-22T11:00:00Z',
    views: 9200,
    likes: 1100,
  },
  {
    id: '6',
    title: 'Data Stream Archangel',
    artist: ARTISTS[1],
    imageUrl: 'https://picsum.photos/seed/archangel/600/400',
    description: 'A celestial being formed from flowing data streams and holographic light.',
    tags: ['Fantasy', 'Sci-Fi', 'Character', 'Holographic'],
    createdAt: '2024-07-20T16:45:00Z',
    views: 11500,
    likes: 1350,
  },
   {
    id: '7',
    title: 'Chrome Horizon',
    artist: ARTISTS[2],
    imageUrl: 'https://picsum.photos/seed/horizon/600/400',
    description: 'A sleek, minimalist landscape reflecting an alien sky. The beauty of desolation.',
    tags: ['Minimalist', 'Sci-Fi', 'Landscape', 'Chrome'],
    createdAt: '2024-07-23T08:00:00Z',
    views: 6800,
    likes: 720,
  },
  {
    id: '8',
    title: 'Aetheric Construct',
    artist: ARTISTS[3],
    imageUrl: 'https://picsum.photos/seed/aether/600/400',
    description: 'An impossible structure held together by pure energy, floating in a nebulous void.',
    tags: ['Abstract', 'Architecture', 'Energy', 'Surreal'],
    createdAt: '2024-07-22T19:30:00Z',
    views: 9900,
    likes: 1050,
  },
   {
    id: '9',
    title: 'Last Stop: Neo-Kyoto',
    artist: ARTISTS[0],
    imageUrl: 'https://picsum.photos/seed/neokyoto/600/400',
    description: 'Rain-slicked streets of a futuristic Kyoto, with towering holographic advertisements.',
    tags: ['Cyberpunk', 'Cityscape', 'Japan', 'Rain'],
    createdAt: '2024-07-24T12:00:00Z',
    views: 13500,
    likes: 1800,
  },
  {
    id: '10',
    title: 'Sentient Nebula',
    artist: ARTISTS[1],
    imageUrl: 'https://picsum.photos/seed/nebula/600/400',
    description: 'A vast cosmic cloud showing signs of consciousness, its colors shifting with thought.',
    tags: ['Space', 'Cosmic', 'Abstract', 'AI Art'],
    createdAt: '2024-07-23T15:10:00Z',
    views: 10200,
    likes: 1150,
  },
  {
    id: '11',
    title: 'Crystal Guardians',
    artist: ARTISTS[2],
    imageUrl: 'https://picsum.photos/seed/guardians/600/400',
    description: 'Ancient crystalline entities protecting a forgotten relic in a hidden cave.',
    tags: ['Fantasy', 'Creature Design', 'Crystal', 'Environment'],
    createdAt: '2024-07-25T09:00:00Z',
    views: 8800,
    likes: 920,
  },
  {
    id: '12',
    title: 'Digital Phoenix',
    artist: ARTISTS[3],
    imageUrl: 'https://picsum.photos/seed/phoenix/600/400',
    description: 'A mythical phoenix reborn from lines of code and digital fire, symbolizing resilience.',
    tags: ['Mythical', 'Digital Art', 'Abstract', 'Symbolic'],
    createdAt: '2024-07-24T17:45:00Z',
    views: 11800,
    likes: 1400,
  }
];